class MessageCode:
	POSSIBLE_HOLE_DETECTED = 1
	POSSIBLE_TRAFFIC_JAM_DETECTED = 2
	POSSIBLE_FIXED_HOLE_DETECTED = 3
	POSSIBLE_NO_TRAFFIC_JAM_DETECTED = 4
	POSSIBLE_BUMP_DETECTED = 5
	POSSIBLE_REMOVED_BUMP_DETECTED = 6
	UPDATE_REQUEST = 7